### ISSUE TITLE
Open source Mayflower repo? Move composer dependencies out of private Palantir repos?

### ISSUE THREAD

**Issue by bryanhirsch** [massgov/openmass#9]
Will `composer install` work to do a full rebuild of the code base? Or does this just work because the download includes things like Mayflower that I wouldn't have access to otherwise?

If Mayflower is going to have a public repo (which I think it needs to), we need to get that in front of Security ASAP.

If we need to get Palantir to open or mirror any of their build dependencies in composer.json (mayflower-artifacts? the-build? other?), we should get those specifics identified and get this ball rolling too.

**Comment by lukewertz** [comment]
https://github.com/massgov/mayflower-artifacts is open (and owned by massgov).

https://github.com/palantirnet/the-build is open (and also available on packagist: https://packagist.org/packages/palantirnet/the-build).

https://packagist.org/packages/palantirnet/the-vagrant is also open and available on packagist.

I don't think there is anything else that needs to be done. I think this can be closed.
